import logging
import os
import shutil
import time
import uuid

from datasets import (
    Features,
    Value,
    concatenate_datasets,
    load_dataset,
    load_from_disk,
)
from datasets.utils.logging import disable_progress_bar
from transformers import AutoTokenizer

logger = logging.getLogger("PlantGeneAnn.src.sequence_tokenizer")

SHARD_SIZE = 50_000


# Explicit CSV schema prevents identifiers such as ``000001`` from being
# inferred as integers and losing their leading zeros. All genomic metadata
# coordinates are stored as signed int64 values throughout the pipeline.
CHUNK_TSV_FEATURES = Features(
    {
        "global_window_index": Value("int64"),
        "chrom_id": Value("string"),
        "chrom_length": Value("int64"),
        "chrom_index": Value("int64"),
        "chrom_window_index": Value("int64"),
        "center_start": Value("int64"),
        "center_end": Value("int64"),
        "chunk_id": Value("int64"),
        "chunk_local_index": Value("int64"),
        "sequence": Value("string"),
    }
)


def _load_chunk_tsv_dataset(tsv_path: str, cache_dir: str):
    """Load one window TSV with stable, lossless column types.

    In particular, ``chrom_id`` is always parsed as a string so numeric-looking
    FASTA identifiers retain leading zeros. ``keep_default_na=False`` also
    preserves identifiers such as ``NA`` as literal strings.
    """

    raw_dataset = load_dataset(
        "csv",
        data_files={"data": tsv_path},
        split="data",
        delimiter="\t",
        features=CHUNK_TSV_FEATURES,
        keep_default_na=False,
        cache_dir=cache_dir,
    )

    missing_columns = set(CHUNK_TSV_FEATURES) - set(raw_dataset.column_names)
    if missing_columns:
        raise ValueError(
            f"Chunk TSV {tsv_path} is missing required metadata columns: "
            f"{sorted(missing_columns)}"
        )

    chrom_id_feature = raw_dataset.features["chrom_id"]
    if getattr(chrom_id_feature, "dtype", None) != "string":
        raise TypeError(
            f"Chunk TSV {tsv_path} loaded chrom_id with type "
            f"{chrom_id_feature!r}; expected Value('string')."
        )

    invalid_chrom_id_rows = [
        row_index
        for row_index, chrom_id in enumerate(raw_dataset["chrom_id"])
        if not isinstance(chrom_id, str) or not chrom_id
    ]
    if invalid_chrom_id_rows:
        raise ValueError(
            f"Chunk TSV {tsv_path} contains null, empty, or non-string chrom_id "
            f"values at rows {invalid_chrom_id_rows[:10]}."
        )

    return raw_dataset


class SequenceTokenizer:
    """Tokenize sequence windows while preserving genomic metadata.

    The input chunk TSV files are generated by ``SequenceExtractor`` and contain
    one row per model-input window. Only the raw ``sequence`` column is removed
    after tokenization; all coordinate/order metadata columns are kept in the
    saved HuggingFace dataset so downstream distributed inference can write
    self-describing window-level HDF5 outputs.

    For large chunks (> ``SHARD_SIZE`` rows) the tokenization is split into
    smaller shards to cap peak memory. Each shard is independently tokenized
    and saved to disk, then all shards are concatenated into the final chunk
    dataset. Shards are removed by default and retained when
    ``keep_datasets=True``.
    """

    REQUIRED_COLUMNS = set(CHUNK_TSV_FEATURES)

    def __init__(self, config, keep_datasets: bool = False):
        self.config = config
        self.keep_datasets = bool(keep_datasets)
        self.cache_dir = os.path.join(config.cache_path, "datasets")
        self.shards_root = os.path.join(config.cache_path, "shards")
        self.shard_run_dir = os.path.join(
            self.shards_root,
            f"run_{os.getpid()}_{uuid.uuid4().hex[:12]}",
        )
        self.tokenizer = AutoTokenizer.from_pretrained(
            self.config.model_path,
            trust_remote_code=True,
            use_fast=True,
        )
        self.max_len = self.config.sequence_length + 2

    def tokenize_function(self, examples):
        """Tokenization function for dataset mapping.

        Uses ``return_tensors=None`` so the tokenizer returns plain Python
        lists instead of PyTorch tensors.  HuggingFace Datasets stores data
        in Arrow format, which handles Python lists natively -- creating
        temporary PyTorch tensors only to immediately convert them back is
        an unnecessary overhead.
        """
        tokenized_sequence = self.tokenizer(
            examples["sequence"],
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors=None,
        )["input_ids"]
        return {"input_ids": tokenized_sequence}

    def _tokenize_shard(self, shard, shard_idx: int, n: int, num_proc: int):
        """Tokenize one shard, save it under the run shard directory, and return its path."""
        batch_size = min(len(shard), num_proc * 100)
        tokenized = shard.map(
            self.tokenize_function,
            batched=True,
            batch_size=batch_size,
            num_proc=num_proc,
            remove_columns=["sequence"],
            desc=f"Chunk {n} shard {shard_idx}",
        )
        os.makedirs(self.shard_run_dir, exist_ok=True)
        shard_path = os.path.join(
            self.shard_run_dir,
            f"chunk_{n}_shard_{shard_idx}",
        )
        tokenized.save_to_disk(shard_path)
        del tokenized
        return shard_path

    def tokenize_chromosome(self, n: int, tsv_path: str, output_dir: str) -> int:
        """Tokenize one chunk TSV and preserve all window metadata columns.

        For chunks with more than ``SHARD_SIZE`` rows the dataset is split
        into smaller shards to keep peak memory bounded.  Each shard is
        tokenized independently, saved under the run shard directory, and the
        final concatenated dataset is written to ``output_dir/chunk_{n}``.
        Intermediate shards are retained only when ``keep_datasets=True``.

        Returns:
            Number of sequence windows successfully tokenized in this chunk.
        """
        try:
            raw_dataset = _load_chunk_tsv_dataset(
                tsv_path=tsv_path,
                cache_dir=self.cache_dir,
            )

            total_rows = len(raw_dataset)
            num_proc = min(total_rows, int(self.config.num_tokenize_proc))
            num_proc = max(1, num_proc)

            if total_rows <= SHARD_SIZE:
                tokenized_chunk = raw_dataset.map(
                    self.tokenize_function,
                    batched=True,
                    batch_size=min(total_rows, num_proc * 100),
                    num_proc=num_proc,
                    remove_columns=["sequence"],
                    desc=f"Tokenizing chunk {n}",
                )
                chr_save_path = os.path.join(output_dir, f"chunk_{n}")
                tokenized_chunk.save_to_disk(chr_save_path)
                del tokenized_chunk
            else:
                shard_paths = []
                for shard_idx in range(0, total_rows, SHARD_SIZE):
                    shard = raw_dataset.select(
                        range(shard_idx, min(shard_idx + SHARD_SIZE, total_rows))
                    )
                    shard_path = self._tokenize_shard(
                        shard, shard_idx // SHARD_SIZE, n, num_proc
                    )
                    shard_paths.append(shard_path)
                    del shard

                logger.debug(
                    "Chunk %d: concatenating %d shards (%d rows)",
                    n, len(shard_paths), total_rows,
                )
                shards = [load_from_disk(p) for p in shard_paths]
                combined = concatenate_datasets(shards)
                chr_save_path = os.path.join(output_dir, f"chunk_{n}")
                combined.save_to_disk(chr_save_path)
                del combined, shards

                if not self.keep_datasets:
                    for p in shard_paths:
                        shutil.rmtree(p, ignore_errors=True)

            return total_rows

        except Exception as e:
            raise RuntimeError(f"Failed to tokenize chunk {n}: {e}") from e

    def process(self, num_chunks: int):
        """Execute tokenization and log one completion record per chunk.

        HuggingFace Datasets progress bars are disabled so ``load_dataset()``,
        ``map()``, and ``save_to_disk()`` do not emit per-chunk or per-shard
        dynamic output. PlantGeneAnn instead reports one stable INFO message
        after each chunk has been fully tokenized and persisted.
        """
        # HuggingFace Datasets 2.15.0 exposes the singular helper from
        # datasets.utils.logging rather than the newer top-level plural API.
        disable_progress_bar()

        try:
            for i in range(num_chunks):
                chunk_number = i + 1
                tsv_path = os.path.join(
                    self.config.cache_path,
                    f"chunk_{chunk_number}.tsv",
                )
                if os.path.exists(tsv_path):
                    chunk_start = time.monotonic()
                    num_windows = self.tokenize_chromosome(
                        chunk_number,
                        tsv_path,
                        self.config.cache_path,
                    )
                    logger.info(
                        "Tokenization chunk %d/%d completed: windows=%d, elapsed=%.1fs",
                        chunk_number,
                        num_chunks,
                        num_windows,
                        time.monotonic() - chunk_start,
                    )
                else:
                    logger.warning("TSV file not found for chunk %d", chunk_number)
        finally:
            if not self.keep_datasets:
                shutil.rmtree(self.shard_run_dir, ignore_errors=True)
                try:
                    os.rmdir(self.shards_root)
                except OSError:
                    # The root can legitimately contain shards retained by a
                    # different run, so remove it only when it is empty.
                    pass

        logger.debug("Tokenization completed")
        return
